### ISSUE TITLE
HTTPError: 561 Server Error: FastReject

### ISSUE THREAD

**Issue by jezhang** [wechat-python-sdk/wechat-python-sdk#29]
ERROR | Internal Server Error: /wx/portal/
Traceback (most recent call last):
  File "/home/jezhang/djangocms/lib/python2.7/site-packages/django/core/handlers/base.py", line 115, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/jezhang/djangocms/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "./weixin/views.py", line 211, in portal
    user_json = wechat.get_user_info(wx_openid,lang='zh_CN')
  File "./wechat_sdk/basic.py", line 547, in get_user_info
    'lang': lang,
  File "./wechat_sdk/basic.py", line 937, in _get
    **kwargs
  File "./wechat_sdk/basic.py", line 921, in _request
    r.raise_for_status()
  File "/home/jezhang/djangocms/lib/python2.7/site-packages/requests/models.py", line 831, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 561 Server Error: FastReject

**Comment by JohnnyZhao** [comment]
这个应该是请求太频繁，被微信拒掉了。我们在生产环境偶尔也会出现一条两条这种错误。
